In [36]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

In [37]:
nose = pd.read_csv('C:/Users/master15/Desktop/0812resnet/nose_0812_result_edit.csv')

In [38]:
nose.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1788 entries, 0 to 1787
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1788 non-null   int64
 1   코 길이        1788 non-null   int64
 2   코 폭         1788 non-null   int64
 3   콧볼 폭        1788 non-null   int64
 4   result      1788 non-null   object
dtypes: int64(4), object(1)
memory usage: 70.0+ KB

In [39]:
nose.head(50)

    Unnamed: 0  코 길이  코 폭  콧볼 폭 result
0            0   192   99   130  짧다.좁다
1            1   223  122   176  짧다.좁다
2            2   196  112   160  짧다.좁다
3            3   175   97   127  짧다.좁다
4            4   255  129   173  길다.좁다
5            5   203  114   156  짧다.좁다
6            6   226  127   175  짧다.좁다
7            7   220  119   162  짧다.좁다
8            8   260  133   188  길다.넓다
9            9   186  105   140  짧다.좁다
10          10   181  101   135  짧다.좁다
11          11   234  124   166  길다.좁다
12          12   205  115   161  짧다.좁다
13          13   249  140   187  길다.넓다
14          14   220  107   139  짧다.좁다
15          15   234  124   178  길다.좁다
16          16   225  124   172  짧다.좁다
17          17   203  116   162  짧다.좁다
18          18   247  130   181  길다.넓다
19          19   247  126   166  길다.좁다
20          20   243  128   174  길다.좁다
21          21   229  139   189  짧다.넓다
22          22   227  114   154  짧다.좁다
23          23   255  132   184  길다.넓다
24          24   238  121   166  길다.좁다
25          25   210  104   132  짧다.좁다
26          26   253  133   180  길다.넓다
27          27   216  125   171  짧다.좁다
28          28   259  136   191  길다.넓다
29          29   193  102   132  짧다.좁다
30          30   215  106   143  짧다.좁다
31          31   200  113   155  짧다.좁다
32          32   233  126   171  길다.좁다
33          33   258  134   188  길다.넓다
34          34   203  105   144  짧다.좁다
35          35   229  116   151  짧다.좁다
36          36   212  119   168  짧다.좁다
37          37   206  128   176  짧다.좁다
38          38   196  111   153  짧다.좁다
39          39   214  113   152  짧다.좁다
40          40   220  112   149  짧다.좁다
41          41   213  113   154  짧다.좁다
42          42   206  104   136  짧다.좁다
43          43   203  112   153  짧다.좁다
44          44   249  138   191  길다.넓다
45          45   239  121   177  길다.좁다
46          46   198  108   149  짧다.좁다
47          47   219  117   165  짧다.좁다
48          48   230  120   162  길다.좁다
49          49   252  148   202  길다.넓다

In [40]:
nose.drop(['Unnamed: 0'],axis=1,inplace=True)

In [41]:
nose

      코 길이  코 폭  콧볼 폭 result
0      192   99   130  짧다.좁다
1      223  122   176  짧다.좁다
2      196  112   160  짧다.좁다
3      175   97   127  짧다.좁다
4      255  129   173  길다.좁다
...    ...  ...   ...    ...
1783   293  159   227  길다.넓다
1784   268  148   208  길다.넓다
1785   257  169   230  길다.넓다
1786   273  161   229  길다.넓다
1787   235  131   178  길다.좁다

[1788 rows x 4 columns]

In [42]:
nose['result'] = pd.factorize(nose['result'])[0]

In [43]:
nose['result'].value_counts()

0    905
2    582
1    225
3     76
Name: result, dtype: int64

In [44]:
nose.head(50)

    코 길이  코 폭  콧볼 폭  result
0    192   99   130       0
1    223  122   176       0
2    196  112   160       0
3    175   97   127       0
4    255  129   173       1
5    203  114   156       0
6    226  127   175       0
7    220  119   162       0
8    260  133   188       2
9    186  105   140       0
10   181  101   135       0
11   234  124   166       1
12   205  115   161       0
13   249  140   187       2
14   220  107   139       0
15   234  124   178       1
16   225  124   172       0
17   203  116   162       0
18   247  130   181       2
19   247  126   166       1
20   243  128   174       1
21   229  139   189       3
22   227  114   154       0
23   255  132   184       2
24   238  121   166       1
25   210  104   132       0
26   253  133   180       2
27   216  125   171       0
28   259  136   191       2
29   193  102   132       0
30   215  106   143       0
31   200  113   155       0
32   233  126   171       1
33   258  134   188       2
34   203  105   144       0
35   229  116   151       0
36   212  119   168       0
37   206  128   176       0
38   196  111   153       0
39   214  113   152       0
40   220  112   149       0
41   213  113   154       0
42   206  104   136       0
43   203  112   153       0
44   249  138   191       2
45   239  121   177       1
46   198  108   149       0
47   219  117   165       0
48   230  120   162       1
49   252  148   202       2

In [45]:
nose.to_csv("nose_0812_encoding_list_edit.csv", encoding='utf-8-sig')